### ISSUE TITLE
Support hatch format of pyproject.toml

### ISSUE THREAD

**Issue by jimisola** [jakecyr/toml-to-requirements#5]
## Overview of Feature

It seems as [hatch dependency format](https://hatch.pypa.io/1.12/config/dependency/) in pyproject.toml is not fully support.

## Why add this feature?

Hatch is pypa's recommended build ecosystem and it used more and more.

## Acceptance Criteria to Meet

* [ ]  [optional dependencies](https://hatch.pypa.io/1.12/config/dependency/#self-referential)

```toml
[project.optional-dependencies]
crypto = [
  "PyJWT",
  "cryptography",
]
dev = [
  "awesome-project[crypto]",
  "black",
]
```

* [ ]  [environment selection](https://hatch.pypa.io/1.12/environment/#selection) [tool.hatch.envs.*], e.g.

```toml
[tool.hatch.envs.test]
dependencies = ["pytest==8.3.2", "pytest-sugar==1.0.0", "pytest-cov==5.0.0"]

[tool.hatch.envs.lint]
detached = true

dependencies = ["black==24.4.2", "flake8==7.1.0", "flake8-pyproject==1.2.3"]
```
